DROP TABLE IF EXISTS oseba CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS zanr CASCADE;
DROP TABLE IF EXISTS nastopa CASCADE;
DROP TABLE IF EXISTS nagrada CASCADE;
DROP TABLE IF EXISTS nosilec CASCADE;
DROP TABLE IF EXISTS dobi CASCADE;

CREATE TABLE oseba (
   id INTEGER PRIMARY KEY, 
   ime text NOT NULL
);
CREATE TABLE film(
id INTEGER PRIMARY KEY,
naslov text NOT NULL);
CREATE TABLE zanr(
id INTEGER PRIMARY KEY,
ime text NOT NULL);
CREATE TABLE nagrada(
id INTEGER PRIMARY KEY,
ime text NOT NULL,
kategorija text NOT NULL);
CREATE TABLE nastopa(
id_filma INTEGER NOT NULL REFERENCES film(id),
id_osebe INTEGER NOT NULL REFERENCES oseba(id));
CREATE TABLE nosilec(
id INTEGER NOT NULL REFERENCES izvajalec(id),
id INTEGER NOT NULL REFERENCES album(id));
CREATE TABLE ima(
id_zanra INTEGER NOT NULL REFERENCES zanr(id),
id_filma INTEGER NOT NULL REFERENCES film(id));

GRANT ALL ON ALL TABLES IN SCHEMA public TO nezah WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO stefandj WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anamarijak WITH GRANT OPTION;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO nezah WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO stefandj WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anamarijak WITH GRANT OPTION;

GRANT CONNECT ON DATABASE banka2019_anamarijak TO javnost;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO javnost;




      




