DROP TABLE IF EXISTS oseba CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS zanr CASCADE;
DROP TABLE IF EXISTS nastopa CASCADE;
DROP TABLE IF EXISTS nagrada CASCADE;
DROP TABLE IF EXISTS nosilec CASCADE;
DROP TABLE IF EXISTS dobi CASCADE;

CREATE TABLE oseba (
   id INTEGER PRIMARY KEY, 
   ime text NOT NULL
);